### ISSUE TITLE
Question - Silverlight Source

### ISSUE THREAD

**Issue by alexbr** [carlospuk/remotepotato#2]
Hi - am I missing something or is the silverlight UI source not in the project? I'd like to build in the ability for remote potato to work with HTTPS because the silverlight client always defaults to HTTP. I need the source to take a look at what's going on.

Thanks!

**Comment by carlospuk** [comment]
Hi Alex

At the moment, the built Silverlight .XAP is included in this repository, but not the source.  This isn't because I don't want to release the source, it's just because I haven't managed to get together a buildable bunch of source files just yet for it.  The various source projects are scattered over various hard drives, partitions, etc.  When I get a moment I'll get the Silverlive source up here too.

Carl

**Comment by alexbr** [comment]
No problem - thanks Carl.
